# 这个 Makefile 文件用来编译所有的本地例题
all:
	cd ./01_如何创建一个类 && make
	cd ./02_构造函数初始化 && make
	cd ./03_函数加不加const && make -i
	cd ./04_内联函数使用 && make
	cd ./05_函数重载 && make
	cd ./06_ctor放在private && make
	cd ./07_passByValueOrReference && make
	cd ./08_ctor形参引用和const测试 && make
	cd ./09_函数体加const和不加可否共存 && make
	cd ./10_friend友元 && make
	cd ./11_相同class的各个object互为friend && make
	cd ./12_操作符重载 && make
	cd ./13_操作符重载非成员函数 && make
	cd ./14_临时对象 && make
	cd ./15_析构函数测试 && make
	cd ./16_static && make
	cd ./17_classTemplate && make
	cd ./18_functionTemplate && make
	cd ./19_namespace && make
	cd ./20_is_a && make
	cd ./21_Delegation && make
	cd ./22_inheritance_is_a && make
	cd ./23_inheritance_virtualk && make
	cd ./24_inheritance_composition && make
	cd ./25_inheritance_composition_2 && make
	cd ./26_conversion_function_1 && make
	cd ./27_conversion_function_2 && make
	cd ./28_pointer-like_classes && make
	cd ./29_namespace_all_flie_test && make
	cd ./30_test_size_strcut && make
	cd ./31_member_template && make
	cd ./32_specialization_模板特化 && make
	cd ./33_partial_specialization_模板偏特化 && make
	cd ./34_partial_specialization_模板偏特化_2 && make
	cd ./35_template_template_parameter_模板模板参数 && make
	cd ./36_test_clang_version && make
	cd ./37_variadic_templates_C11 && make
	cd ./38_auto_C11 && make
	cd ./39_ranged_base_for_C11 && make
	cd ./40_reference && make
	cd ./41_reference2 && make
	cd ./42_ObjectModel && make
	cd ./43_dynamic_binding && make
	cd ./44_new_delete_test && make
	cd ./45_new_delete_member && make
	cd ./46_new_delete_member2 && make
	cd ./47_newHeadFile && make
	cd ./49_variadicTemplates && make
	cd ./50_SpaceInTemplateExpressions && make -i
	cd ./51_nullptr && make
	cd ./52_auto && make
	cd ./53_Uniform_Initialization && make
	cd ./54_Initializer_Lists && make -i
	cd ./55_initializer_list && make
	cd ./56_initializer_list && make
	cd ./57_initializer_list && make
	cd ./58_explicit_for_ctor && make
	cd ./59_range_based_for_statement && make
	cd ./60_default_delete && make
	cd ./61_lambdas && make

clean:
	cd ./01_如何创建一个类 && make clean
	cd ./02_构造函数初始化 && make clean
	cd ./03_函数加不加const && make clean
	cd ./04_内联函数使用 && make clean
	cd ./05_函数重载 && make clean
	cd ./06_ctor放在private && make clean
	cd ./07_passByValueOrReference && make clean
	cd ./08_ctor形参引用和const测试 && make clean
	cd ./09_函数体加const和不加可否共存 && make clean
	cd ./10_friend友元 && make clean
	cd ./11_相同class的各个object互为friend && make clean
	cd ./12_操作符重载 && make clean
	cd ./13_操作符重载非成员函数 && make clean
	cd ./14_临时对象 && make clean
	cd ./15_析构函数测试 && make clean
	cd ./16_static && make clean
	cd ./17_classTemplate && make clean
	cd ./18_functionTemplate && make clean
	cd ./19_namespace && make clean
	cd ./20_is_a && make clean
	cd ./21_Delegation && make clean
	cd ./22_inheritance_is_a && make clean
	cd ./23_inheritance_virtualk && make clean
	cd ./24_inheritance_composition && make clean
	cd ./25_inheritance_composition_2 && make clean
	cd ./26_conversion_function_1 && make clean
	cd ./27_conversion_function_2 && make clean
	cd ./28_pointer-like_classes && make clean
	cd ./29_namespace_all_flie_test && make clean
	cd ./30_test_size_strcut && make clean
	cd ./31_member_template && make clean
	cd ./32_specialization_模板特化 && make clean
	cd ./33_partial_specialization_模板偏特化 && make clean
	cd ./34_partial_specialization_模板偏特化_2 && make clean
	cd ./35_template_template_parameter_模板模板参数 && make clean
	cd ./36_test_clang_version && make clean
	cd ./37_variadic_templates_C11 && make clean
	cd ./38_auto_C11 && make clean
	cd ./39_ranged_base_for_C11 && make clean
	cd ./40_reference && make clean
	cd ./41_reference2 && make clean
	cd ./42_ObjectModel && make clean
	cd ./43_dynamic_binding && make clean
	cd ./44_new_delete_test && make clean
	cd ./45_new_delete_member && make clean
	cd ./46_new_delete_member2 && make clean
	cd ./47_newHeadFile && make clean
	cd ./49_variadicTemplates && make clean
	cd ./50_SpaceInTemplateExpressions && make clean
	cd ./51_nullptr && make clean
	cd ./52_auto && make clean
	cd ./53_Uniform_Initialization && make clean
	cd ./54_Initializer_Lists && make clean
	cd ./55_initializer_list && make clean
	cd ./56_initializer_list && make clean
	cd ./57_initializer_list && make clean
	cd ./58_explicit_for_ctor && make clean
	cd ./59_range_based_for_statement && make clean
	cd ./60_default_delete && make clean
	cd ./61_lambdas && make clean

