CC=clang
OBJ=main errone errtwo errthr errfou 
RM=rm -f

all:$(OBJ)

main:main.c
	$(CC) -o main main.c

errone:errone.c
	$(CC) -o errone errone.c

errtwo:errtwo.c
	$(CC) -o errtwo errtwo.c

errthr:errthr.c
	$(CC) -o errthr errthr.c

errfou:errfou.c
	$(CC) -o errfou errfou.c

clean:
	$(RM) $(OBJ) *.o 

