# 这个 Makefile 文件用来编译所有的本地例题
all:
	cd ./chapter_02 && make
	cd ./chapter_03 && make
	cd ./chapter_04 && make
	cd ./chapter_05 && make
	cd ./chapter_06 && make
	cd ./chapter_07 && make
	cd ./chapter_08 && make

clean:
	cd ./chapter_02 && make clean
	cd ./chapter_03 && make clean
	cd ./chapter_04 && make clean
	cd ./chapter_05 && make clean
	cd ./chapter_06 && make clean
	cd ./chapter_07 && make clean
	cd ./chapter_08 && make clean
