# 这个 Makefile 文件用来编译所有的本地例题
all:
	cd ./01 && make
	cd ./02 && make
	cd ./03 && make
	cd ./04 && make
	cd ./05 && make
	cd ./06 && make
	cd ./07 && make
	cd ./08 && make
	cd ./09 && make

clean:
	cd ./01 && make clean
	cd ./02 && make clean
	cd ./03 && make clean
	cd ./04 && make clean
	cd ./05 && make clean
	cd ./06 && make clean
	cd ./07 && make clean
	cd ./08 && make clean
	cd ./09 && make clean
